### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by ousamabenyounes** [Stormrage74/downloader9000#1]
Hi @Stormrage74 

Your parameters.yml files have been compromised and your login/pwd are now visible on this this project
to remove it from your history:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Change your login/pwd on all your projects...

I recommand you also to use a gitignore file on the root of your Symfony project:
https://github.com/github/gitignore/blob/master/Symfony.gitignore
This will automatically ignore your parameters.yml file, your vendors ...

I also recommand you to plug your open source symfony project to sensioInsight...It's free and help you find all security, performance or quality issue on each commit

https://insight.sensiolabs.com/

Hope this will help you :)

I also recommand you to add a gitignore file on your project to remove vendors and cache from repo

**Comment by Stormrage74** [comment]
Hi @ousamabenyounes,

Thanks a lot for pointing this issue :) . Looks like im a bit tired. I'll change password compromise. I was impressed by your reactivity :) Hopefully im a bit paranoiac with to much level of security so that it was very localized. I'll also check out for sensioInsight, it was a good oportunity to do it.

Thanks again !

**Comment by ousamabenyounes** [comment]
Hi @Stormrage74, 
happy to see that this isssue helped you :).
We all make mistake, and when you're tired, that means that you should take some vaccations and rest...I would also love to do it :(...
and Also happy to see that this issue didn't point any problem for you :).

I should recommand you to remove vendors from your repository so your repo will be more light .
And if you need vendors, you just have to install them locally with composer later.

Have a good day and good luck for your projects!

Regards,
Ousama.
